services:
  - type: web
    name: aadhaar-satark
    runtime: python
    rootDir: .
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATA_GOV_API_KEY
        sync: false
